project_id = "jeiuruhneitvfyjkmbvj"
[functions.findMatchingItinerary]
enabled = true
verify_jwt = true
import_map = "./import_map.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/findMatchingItinerary/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/findMatchingItinerary/*.html" ]

[functions.findMatchingItineraryBackup]
enabled = true
verify_jwt = false
import_map = "./import_map.json"
entrypoint = "./functions/findMatchingItineraryBackup/index.ts"

[functions.contact-inquiry]
enabled = true
verify_jwt = false
import_map = "./import_map.json"
entrypoint = "./functions/contact-inquiry/index.ts"
